export { default as AppLayout } from './AppLayout'
export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as Home } from './Home'
export { default as DetailProduct } from './DetailProduct'