export { default as AppLayout } from './AppLayout'
export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as Home } from './Home'
export { default as Profile } from './Profile'
export { default as DetailProduct } from './DetailProduct'
export { default as OrderList } from './OrderList'
export { default as Pay } from './Pay'
export { default as Promotion } from './Promotion'
export { default as Store } from './Store'

export { default as NotFound } from './NotFound'