export {default as Loading } from './Loading'
export {default as TitleContent } from './TitleContent'
export {default as ButtonCreate } from './ButtonCreate'
export {default as ButtonAction } from './ButtonAction'
export {default as Slider } from './Slider'